sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: OljvTidrQGy7ExI0QmSD27Su0o9Myl9+FJDsH39HSyiEJPp0sF2wjYvb1aEKARxVUR6W4Yvesw4yAPY/8Mw8wBzxPmyAXM9jtb3pgLTR2UCL7y+8L+GfOCf1TZdt28pdzMJgtMmTo2f/lgYNtNJ1hzitMYnvU/qV4QgAeiH2p4bqODznAe6O6v+r/VIam3NjXeKfXToguHO6IEjMHlg3dQhHdLt8P4oyvaVBilqokNhLctV36d1fW+uyfWnug7/EGIOete8VxhTnuxiA6BB8G/QVx0B5enmIwqYSZEd8thOz7fdQBKeTYAj7AAf3BD6hET5+FvBF7zBLOvEqH0Wnpg0SWT/CdA8Uglp9Ird7VP0nh7VIavmV2udL3m8MB/0uT40RWlbAhfwbg72Tv6yk3bF8XbT4NgP06xGT+CRqU7qLjDYfIhqKj3jhUBbnOj1rv7GfNg1ebxTHKXn6FeHU5Y6iMc1Kwxg09kqM9HllBHtZd1Osh//NfSf5iMnMGbnvqL2ZpA98J26hjWnReMlY+3/FogN5BJ5I9c5nHN1fCj413QnhvueeXaTjyWUJ0lBQXMIvBgkb0pXVxsWr5T+suuMDrYpmXgbQFJaCPUNk7zEtka1XvyioPHn2ZUAnB1ROX9HmK/KAAhByMyyFZVb8OLvB1Nk7ik+yJ+HlKTski04=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Serapis-Volume-03_5503
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy